In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
!pwd

/content

In [16]:
path_week_1 = "./drive/MyDrive/Study/zoom_participants_83169866693.xls"
path_week_2 = "./drive/MyDrive/Study/zoom_participants_86750070616.xls"

**학생만 남기고 필터링**

In [103]:
df_1 = pd.read_excel(path_week_1)
df_2 = pd.read_excel(path_week_2)

df_1 = df_1[~(df_1.역할.isin(['교수자']))]
df_2 = df_2[~(df_2.역할.isin(['교수자']))]

display(df_1.head())
display(df_2.head())

   번호        학번   이름  역할            참여시작시간            참여종료시간      참여시간
1   2  K2021504  유혁문  학생  2021-09-04 16:01  2021-09-04 17:46  01:45:29
2   3  K2021020  노용문  학생  2021-09-04 16:01  2021-09-04 17:46  01:45:33
3   4  K2020510  우윤우  학생  2021-09-04 16:01  2021-09-04 17:46  01:45:25
4   5  K2021027  오지수  학생  2021-09-04 16:01  2021-09-04 17:46  01:45:27
5   6  K2021017  김채현  학생  2021-09-04 16:01  2021-09-04 17:47  01:45:38

   번호        학번   이름  역할            참여시작시간            참여종료시간      참여시간
1   2  K2021017  김채현  학생  2021-09-11 15:58  2021-09-11 17:50  01:52:15
2   3  K2021035  홍성규  학생  2021-09-11 15:58  2021-09-11 17:50  01:52:01
3   4  K2021033  조윤정  학생  2021-09-11 15:58  2021-09-11 17:50  01:51:58
4   5  K2021029  이범찬  학생  2021-09-11 15:58  2021-09-11 17:50  01:51:46
5   6  K2020511  윤영선  학생  2021-09-11 15:58  2021-09-11 17:50  01:51:55

**필요한 컬럼만 남김**

In [104]:
# 이름 학과 학번 1주차 2주차
key_filter = ['이름', '학번', '참여시작시간']
df_1 = df_1[key_filter]
df_2 = df_2[key_filter]
display(df_1.head())
display(df_2.head())

    이름        학번            참여시작시간
1  유혁문  K2021504  2021-09-04 16:01
2  노용문  K2021020  2021-09-04 16:01
3  우윤우  K2020510  2021-09-04 16:01
4  오지수  K2021027  2021-09-04 16:01
5  김채현  K2021017  2021-09-04 16:01

    이름        학번            참여시작시간
1  김채현  K2021017  2021-09-11 15:58
2  홍성규  K2021035  2021-09-11 15:58
3  조윤정  K2021033  2021-09-11 15:58
4  이범찬  K2021029  2021-09-11 15:58
5  윤영선  K2020511  2021-09-11 15:58

**문자열로부터 시간 필터링**

In [105]:
key_apply, func_apply = '참여시작시간', lambda d: d[:11]
df_1[key_apply] = df_1.참여시작시간.apply(func_apply)
df_2[key_apply] = df_2.참여시작시간.apply(func_apply)
display(df_1.head())
display(df_2.head())

    이름        학번       참여시작시간
1  유혁문  K2021504  2021-09-04
2  노용문  K2021020  2021-09-04
3  우윤우  K2020510  2021-09-04
4  오지수  K2021027  2021-09-04
5  김채현  K2021017  2021-09-04

    이름        학번       참여시작시간
1  김채현  K2021017  2021-09-11
2  홍성규  K2021035  2021-09-11
3  조윤정  K2021033  2021-09-11
4  이범찬  K2021029  2021-09-11
5  윤영선  K2020511  2021-09-11

**학번으로 중복제거**

In [106]:
df_1 = df_1.drop_duplicates('학번').reset_index()
df_2 = df_2.drop_duplicates('학번').reset_index()
display(df_1.head())
display(df_2.head())

   index   이름        학번       참여시작시간
0      1  유혁문  K2021504  2021-09-04
1      2  노용문  K2021020  2021-09-04
2      3  우윤우  K2020510  2021-09-04
3      4  오지수  K2021027  2021-09-04
4      5  김채현  K2021017  2021-09-04

   index   이름        학번       참여시작시간
0      1  김채현  K2021017  2021-09-11
1      2  홍성규  K2021035  2021-09-11
2      3  조윤정  K2021033  2021-09-11
3      4  이범찬  K2021029  2021-09-11
4      5  윤영선  K2020511  2021-09-11

**불필요한 컬럼 제거 및 중복되는 컬럼명 수정**

In [107]:
df_1 = df_1.rename(columns={'참여시작시간':'1주차'})
df_2 = df_2.rename(columns={'참여시작시간':'2주차'})
df_1 = df_1.drop(['index'], axis=1)
df_2 = df_2.drop(['index'], axis=1)
display(df_1)
display(df_2)

     이름        학번          1주차
0   유혁문  K2021504  2021-09-04
1   노용문  K2021020  2021-09-04
2   우윤우  K2020510  2021-09-04
3   오지수  K2021027  2021-09-04
4   김채현  K2021017  2021-09-04
5   이효중  K2021030  2021-09-04
6   최원호  K2020514  2021-09-04
7   이문용  K2021505  2021-09-04
8   박준호  K2021501  2021-09-04
9   정민욱  K2021507  2021-09-04
10  윤영선  K2020511  2021-09-04
11  조윤정  K2021033  2021-09-04
12  김형준  K2021018  2021-09-04
13  임항빈  K2021032  2021-09-04
14  이범찬  K2021029  2021-09-04
15  임준혁  K2021031  2021-09-04
16  김봉상  K2021014  2021-09-04
17  이해수  K2021506  2021-09-04
18  오동규  K2021503  2021-09-04
19  김용욱  K2021015  2021-09-04
20  남용휘  K2021019  2021-09-04
21  성희정  K2021502  2021-09-04
22  신용주  K2021022  2021-09-04
23  곽승준  K2021012  2021-09-04
24  조애자  K2020506  2021-09-04
25  홍성규  K2021035  2021-09-04
26  안혜영  K2021024  2021-09-04

     이름        학번          2주차
0   김채현  K2021017  2021-09-11
1   홍성규  K2021035  2021-09-11
2   조윤정  K2021033  2021-09-11
3   이범찬  K2021029  2021-09-11
4   윤영선  K2020511  2021-09-11
5   유혁문  K2021504  2021-09-11
6   남용휘  K2021019  2021-09-11
7   임항빈  K2021032  2021-09-11
8   김형준  K2021018  2021-09-11
9   이문용  K2021505  2021-09-11
10  이효중  K2021030  2021-09-11
11  박준호  K2021501  2021-09-11
12  조애자  K2020506  2021-09-11
13  곽승준  K2021012  2021-09-11
14  신용주  K2021022  2021-09-11
15  오동규  K2021503  2021-09-11
16  김봉상  K2021014  2021-09-11
17  이해수  K2021506  2021-09-11
18  김용욱  K2021015  2021-09-11
19  노용문  K2021020  2021-09-11
20  임준혁  K2021031  2021-09-11
21  정민욱  K2021507  2021-09-11
22  안혜영  K2021024  2021-09-11
23  오지수  K2021027  2021-09-11
24  우윤우  K2020510  2021-09-11
25  성희정  K2021502  2021-09-11
26  최원호  K2020514  2021-09-11

**Outer join**

In [108]:
df_3 = pd.merge(df_1, df_2, how='outer', on=['학번', '이름'])
df_3

     이름        학번          1주차          2주차
0   유혁문  K2021504  2021-09-04   2021-09-11
1   노용문  K2021020  2021-09-04   2021-09-11
2   우윤우  K2020510  2021-09-04   2021-09-11
3   오지수  K2021027  2021-09-04   2021-09-11
4   김채현  K2021017  2021-09-04   2021-09-11
5   이효중  K2021030  2021-09-04   2021-09-11
6   최원호  K2020514  2021-09-04   2021-09-11
7   이문용  K2021505  2021-09-04   2021-09-11
8   박준호  K2021501  2021-09-04   2021-09-11
9   정민욱  K2021507  2021-09-04   2021-09-11
10  윤영선  K2020511  2021-09-04   2021-09-11
11  조윤정  K2021033  2021-09-04   2021-09-11
12  김형준  K2021018  2021-09-04   2021-09-11
13  임항빈  K2021032  2021-09-04   2021-09-11
14  이범찬  K2021029  2021-09-04   2021-09-11
15  임준혁  K2021031  2021-09-04   2021-09-11
16  김봉상  K2021014  2021-09-04   2021-09-11
17  이해수  K2021506  2021-09-04   2021-09-11
18  오동규  K2021503  2021-09-04   2021-09-11
19  김용욱  K2021015  2021-09-04   2021-09-11
20  남용휘  K2021019  2021-09-04   2021-09-11
21  성희정  K2021502  2021-09-04   2021-09-11
22  신용주  K2021022  2021-09-04   2021-09-11
23  곽승준  K2021012  2021-09-04   2021-09-11
24  조애자  K2020506  2021-09-04   2021-09-11
25  홍성규  K2021035  2021-09-04   2021-09-11
26  안혜영  K2021024  2021-09-04   2021-09-11

**학과 삽입**

In [109]:
df_3.insert(1, '학과', ['인공지능전공']*len(df_3))
display(df_3)

     이름      학과        학번          1주차          2주차
0   유혁문  인공지능전공  K2021504  2021-09-04   2021-09-11
1   노용문  인공지능전공  K2021020  2021-09-04   2021-09-11
2   우윤우  인공지능전공  K2020510  2021-09-04   2021-09-11
3   오지수  인공지능전공  K2021027  2021-09-04   2021-09-11
4   김채현  인공지능전공  K2021017  2021-09-04   2021-09-11
5   이효중  인공지능전공  K2021030  2021-09-04   2021-09-11
6   최원호  인공지능전공  K2020514  2021-09-04   2021-09-11
7   이문용  인공지능전공  K2021505  2021-09-04   2021-09-11
8   박준호  인공지능전공  K2021501  2021-09-04   2021-09-11
9   정민욱  인공지능전공  K2021507  2021-09-04   2021-09-11
10  윤영선  인공지능전공  K2020511  2021-09-04   2021-09-11
11  조윤정  인공지능전공  K2021033  2021-09-04   2021-09-11
12  김형준  인공지능전공  K2021018  2021-09-04   2021-09-11
13  임항빈  인공지능전공  K2021032  2021-09-04   2021-09-11
14  이범찬  인공지능전공  K2021029  2021-09-04   2021-09-11
15  임준혁  인공지능전공  K2021031  2021-09-04   2021-09-11
16  김봉상  인공지능전공  K2021014  2021-09-04   2021-09-11
17  이해수  인공지능전공  K2021506  2021-09-04   2021-09-11
18  오동규  인공지능전공  K2021503  2021-09-04   2021-09-11
19  김용욱  인공지능전공  K2021015  2021-09-04   2021-09-11
20  남용휘  인공지능전공  K2021019  2021-09-04   2021-09-11
21  성희정  인공지능전공  K2021502  2021-09-04   2021-09-11
22  신용주  인공지능전공  K2021022  2021-09-04   2021-09-11
23  곽승준  인공지능전공  K2021012  2021-09-04   2021-09-11
24  조애자  인공지능전공  K2020506  2021-09-04   2021-09-11
25  홍성규  인공지능전공  K2021035  2021-09-04   2021-09-11
26  안혜영  인공지능전공  K2021024  2021-09-04   2021-09-11

**날짜가 존재하는 값들은 O로 대치**

In [110]:
import numpy as np
df_3['1주차'] = df_3['1주차'].apply(lambda s: 'X' if s==np.NaN else 'O')
df_3['2주차'] = df_3['2주차'].apply(lambda s: 'X' if s==np.NaN else 'O')
df_3

     이름      학과        학번 1주차 2주차
0   유혁문  인공지능전공  K2021504   O   O
1   노용문  인공지능전공  K2021020   O   O
2   우윤우  인공지능전공  K2020510   O   O
3   오지수  인공지능전공  K2021027   O   O
4   김채현  인공지능전공  K2021017   O   O
5   이효중  인공지능전공  K2021030   O   O
6   최원호  인공지능전공  K2020514   O   O
7   이문용  인공지능전공  K2021505   O   O
8   박준호  인공지능전공  K2021501   O   O
9   정민욱  인공지능전공  K2021507   O   O
10  윤영선  인공지능전공  K2020511   O   O
11  조윤정  인공지능전공  K2021033   O   O
12  김형준  인공지능전공  K2021018   O   O
13  임항빈  인공지능전공  K2021032   O   O
14  이범찬  인공지능전공  K2021029   O   O
15  임준혁  인공지능전공  K2021031   O   O
16  김봉상  인공지능전공  K2021014   O   O
17  이해수  인공지능전공  K2021506   O   O
18  오동규  인공지능전공  K2021503   O   O
19  김용욱  인공지능전공  K2021015   O   O
20  남용휘  인공지능전공  K2021019   O   O
21  성희정  인공지능전공  K2021502   O   O
22  신용주  인공지능전공  K2021022   O   O
23  곽승준  인공지능전공  K2021012   O   O
24  조애자  인공지능전공  K2020506   O   O
25  홍성규  인공지능전공  K2021035   O   O
26  안혜영  인공지능전공  K2021024   O   O

**엑셀로 내보내기**

In [117]:
df_3.to_excel("./drive/MyDrive/Study/[기계학습 기초]/전자출석부 텍스트 출석부_기계학습기초_01분반.xls", index=False)